source 'https://rubygems.org'
ruby '~> 2.5'

gem 'berkshelf', '>= 7.0.0'
gem 'chef', '15.3.14'
gem 'chefspec', '>= 7.0.0'
gem 'kitchen-inspec'

gem 'test-kitchen'

gem 'kitchen-docker'
gem 'kitchen-dokken'

gem 'kitchen-ec2'

# Provides `sftp` transport to test-kitchen for faster cookbook upload.
gem 'kitchen-sync'
