source 'https://rubygems.org'
ruby '~> 2.5'

gem 'berkshelf', '>= 7.0.0'
gem 'chef', '15.3.14'
gem 'chefspec', '>= 7.0.0'
gem 'kitchen-inspec', '>= 0.23.0'

gem 'test-kitchen', '>= 2.0.0'

gem 'kitchen-docker', '>= 2.7.0'
gem 'kitchen-dokken', '>= 2.6.7'

gem 'kitchen-ec2', '>= 2.2.2'

# Provides `sftp` transport to test-kitchen for faster cookbook upload.
gem 'kitchen-sync', '>= 2.2.1'
